# Generated by Django 6.0.5 on 2026-05-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_attachments/'),
        ),
    ]
