# Generated by Django 6.0.5 on 2026-05-10 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
