# Generated by Django 6.0.5 on 2026-05-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_attachments/%Y/%M/%D'),
        ),
    ]
